<?php

namespace App\Repositories;

use App\Models\Matchsheet;
use App\Models\Team;

class MatchSheetRepository extends Repository implements IMatchSheetRepository
{

    public function __construct(Matchsheet $matchsheet)
    {
        parent::__construct($matchsheet);
    }

    public function all($orderBy = ['created_at' => 'desc'])
    {
        return parent::all($orderBy); // TODO: Change the autogenerated stub
    }

    public function find($id)
    {
        return parent::find($id); // TODO: Change the autogenerated stub
    }

    public function create(array $data)
    {
        $data['team_a_data']=json_encode($data['team_a_data']);
        $data['team_b_data']=json_encode($data['team_b_data']);
        $data['coaching_staff']=json_encode($data['coaching_staff']);
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function update($id, array $data)
    {
        $currentMatchSheet=parent::find($id);
        $data['team_a_id']= $data['team_a_id'] ?? $currentMatchSheet->team_a_id;
        $data['team_b_id']= $data['team_b_id'] ?? $currentMatchSheet->team_b_id;
        $data['color_a']= $data['color_a'] ?? $currentMatchSheet->color_a;
        $data['color_b']= $data['color_b'] ?? $currentMatchSheet->color_b;
        $data['formation']= $data['formation'] ?? $currentMatchSheet->formation;
        $data['match_date']= $data['match_date'] ?? $currentMatchSheet->match_date;
        $data['location']= $data['location'] ?? $currentMatchSheet->location;
        $data['referee']= $data['referee'] ?? $currentMatchSheet->referee;

        $data['team_a_data']=isset($data['team_a_data'])?
            json_encode($data['team_a_data']):$currentMatchSheet->team_a_data;
        $data['team_b_data']=isset($data['team_b_data'])?
            json_encode($data['team_b_data']):$currentMatchSheet->team_b_data;
        $data['coaching_staff']=isset($data['coaching_staff'])?
            json_encode($data['coaching_staff']):$currentMatchSheet->coaching_staff;
        return parent::update($id, $data); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }
    public function getLast(){
        return Matchsheet::last();
    }

    public function getTeams(){
        return Team::orderBy('name','asc')->get();
    }

}
