<?php

namespace App\Repositories;

use App\Models\Matchsheet;

class MatchSheetRepository extends Repository
{

    public function __construct(Matchsheet $matchsheet)
    {
        parent::__construct($matchsheet);
    }

    public function all($orderBy = ['created_at' => 'desc'])
    {
        return parent::all($orderBy); // TODO: Change the autogenerated stub
    }

    public function find($id)
    {
        return parent::find($id); // TODO: Change the autogenerated stub
    }

    public function create(array $data)
    {
        $data['team_a_data']=json_encode($data['team_a_data']);
        $data['team_b_data']=json_encode($data['team_b_data']);
        $data['coaching_staff']=json_encode($data['coaching_staff']);
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function update($id, array $data)
    {
        $currentMatchSheet=parent::find($id);
        $data['team_a_id']= $data['team_a_id'] ?? $currentMatchSheet->team_a_id;
        $data['team_b_id']= $data['team_b_id'] ?? $currentMatchSheet->team_b_id;
        $data['formation']= $data['formation'] ?? $currentMatchSheet->formation;
        $data['match_date']= $data['match_date'] ?? $currentMatchSheet->match_date;
        $data['location']= $data['location'] ?? $currentMatchSheet->location;
        $data['referee']= $data['referee'] ?? $currentMatchSheet->referee;

        $data['team_a_data']=isset($data['team_a_data'])?
            json_encode($data['team_a_data']):$currentMatchSheet->team_a_data;
        $data['team_b_data']=isset($data['team_b_data'])?
            json_encode($data['team_b_data']):$currentMatchSheet->team_b_data;
        $data['coaching_staff']=isset($data['coaching_staff'])?
            json_encode($data['coaching_staff']):$currentMatchSheet->coaching_staff;
        return parent::update($id, $data); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }
    public function getLast(){
        return Matchsheet::last();
    }

    /*public function findById($id)
    {
        return parent::findById($id); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function update(array $input, $id)
    {
        $currentMatchSheet=parent::findById($id);
        $input['team_a_data']=isset($input['team_a_data'])?
            json_encode($input['team_a_data']):$currentMatchSheet->team_a_data;
        $input['team_b_data']=isset($input['team_b_data'])?
            json_encode($input['team_b_data']):$currentMatchSheet->team_b_data;
        $input['coaching_staff']=isset($input['coaching_staff'])?
            json_encode($input['coaching_staff']):$currentMatchSheet->coaching_staff;
        return parent::update($input, $id); // TODO: Change the autogenerated stub
    }

    public function create(array $input)
    {
        $input['team_a_data']=json_encode($input['team_a_data']);
        $input['team_b_data']=json_encode($input['team_b_data']);
        $input['coaching_staff']=json_encode($input['coaching_staff']);
        return parent::create($input); // TODO: Change the autogenerated stub
    }

    public function findAll(){
        return Matchsheet::orderBy('created_at','desc')->get();
    }
    public function getLast(){
        return Matchsheet::last();
    }*/

}
