<?php

namespace App\Repositories;

use App\Http\Resources\TeamResource;
use App\Models\Team;
use Illuminate\Support\Str;

class TeamRepository extends Repository
{
    public function __construct(Team $team)
    {
        parent::__construct($team);
    }

    public function all($orderBy = ['name' => 'asc'])
    {
        return new TeamResource(parent::all($orderBy)); // TODO: Change the autogenerated stub
    }

    public function find($id)
    {
        return new TeamResource(parent::find($id));
        // return ; TODO: Change the autogenerated stub
    }

    public function create(array $data)
    {
        $data['slugname']=Str::slug($data['name']);
        $data['name']=Str::title($data['name']);
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function update($id, array $data)
    {
        $currentTeam=parent::find($id);
        $data['name']=isset($data['name'])? Str::title($data['name']):$currentTeam->name;
        $data['logo']= $data['logo'] ?? $currentTeam->logo;
        $data['slugname']=isset($data['name'])? Str::slug($data['name']):$currentTeam->slugname;
        return parent::update($id, $data); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

}
